const { NODE_ENV } = process.env;
module.exports = {
  DEFAULT_PORT: NODE_ENV === 'production' ? 3000 : 3001,
  SECRET_KEY: 'vasyapetrov',
  BAD_REQUEST_ERROR: 400,
  BAD_REQUEST_MESSAGE: 'Bad request. Check request data and try again',
  UNAUTHORIZED_ERR: 401,
  UNAUTHORIZED_MESSAGE: 'Email and/or password are wrong',
  UNAUTHORIZED_MESSAGE_TOKEN: 'Authorization error',
  FORBIDDEN_ERR: 403,
  FORBIDDEN_MESSAGE: 'You can delete ONLY yours cards',
  NOT_FOUND_ERR: 404,
  NOT_FOUND_MESSAGE: 'There\'s not such data in database',
  NOT_FOUND_ROUTE: 'The requested page is not found',
  CONFLICT_ERR: 409,
  CONFLICT_MESSAGE: 'Email is already used',
  INTERNAL_SERVER_ERROR: 500,
  INTERNAL_SERVER_MESSAGE: 'Unknown error. Please check!',
  URL_REGEXP: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&//=]*)/i,
  ALLOWED_CORS: [
    'http://localhost:3000',
    'http://mesto-ali.nomoredomains.xyz',
    'https://mesto-ali.nomoredomains.xyz',
  ],
  DEFAULT_ALLOWED_METHODS: 'GET,HEAD,PUT,PATCH,POST,DELETE',
};
